required = ["github.com/onsi/ginkgo/ginkgo"]

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  branch = "master"
  name = "github.com/nu7hatch/gouuid"

[prune]
  go-tests = true
  non-go = true
  unused-packages = true
